/**
 * TernakOS Default Task Templates — Sapi Penggemukan
 * Berdasarkan SNI feedlot sapi potong Indonesia.
 *
 * Semua tanggal menggunakan offset relatif dari batch.start_date.
 * Insert function konversi: addDays(batchStartDate, phase_X_offset)
 *
 * task_type enum:      'timbang' | 'vaksinasi' | 'pakan' | 'kesehatan' | 'kebersihan_kandang' | 'reproduksi' | 'lainnya'
 * recurring_type enum: 'harian' | 'mingguan' | 'dua_mingguan' | 'bulanan' | 'custom' | 'sekali'
 */

// ── TEMPLATE 150 HARI (INTENSIF) ─────────────────────────────────────────────

export const TEMPLATE_150_HARI = [

  // ── FASE ADAPTASI (Hari 1–14, offset 0–13) ───────────────────────────────

  {
    title: 'Timbang awal (berat masuk bakalan)',
    description: 'Timbang semua bakalan untuk mencatat berat awal sebagai baseline perhitungan ADG.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Observasi kondisi bakalan baru',
    description: 'Periksa kondisi fisik, nafsu makan, dan tanda stres pada bakalan yang baru masuk.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Beri pakan adaptasi (hijauan 80%)',
    description: 'Berikan hijauan 80% + konsentrat 20% untuk adaptasi sistem pencernaan bakalan baru.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Cek minum & kebersihan tempat minum',
    description: 'Pastikan tempat minum terisi penuh, bersih, dan tidak ada kotoran atau lumut.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, ganti alas, dan pastikan ventilasi kandang berfungsi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Vaksinasi SE + Anthrax',
    description: 'Berikan vaksin Septicemia Epizootica (SE) dan Anthrax sesuai dosis anjuran dokter hewan.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 2,
    phase_end_offset: 2,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Obat cacing (Albendazole)',
    description: 'Berikan Albendazole sesuai bobot badan untuk eliminasi parasit internal bakalan.',
    task_type: 'obat_cacing',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 6,
    phase_end_offset: 6,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Timbang akhir fase adaptasi',
    description: 'Timbang untuk evaluasi performa awal dan konfirmasi adaptasi pakan berjalan baik.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 13,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },

  // ── FASE GROWING (Hari 15–120, offset 14–119) ─────────────────────────────

  {
    title: 'Beri pakan pagi (konsentrat 60%)',
    description: 'Pemberian pakan pagi: konsentrat 60% + hijauan 40%. Pastikan semua sapi mendapat porsi merata.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Beri pakan sore',
    description: 'Pemberian pakan sore. Pastikan tempat pakan bersih dari sisa pakan sebelumnya.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kesehatan harian',
    description: 'Amati nafsu makan, postur, mata, dan hidung. Catat sapi yang menunjukkan tanda tidak sehat.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, ganti alas, dan pastikan ventilasi kandang berfungsi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Timbang rutin 2 mingguan',
    description: 'Timbang seluruh populasi untuk monitor ADG (Average Daily Gain) fase growing.',
    task_type: 'timbang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Cek & isi stok pakan',
    description: 'Periksa ketersediaan stok konsentrat dan hijauan. Laporkan jika stok tersisa untuk < 7 hari.',
    task_type: 'pakan',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Semprot desinfektan kandang',
    description: 'Semprot desinfektan di seluruh area kandang, termasuk sekat dan tempat minum.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Vaksinasi booster bulanan',
    description: 'Berikan vaksinasi booster sesuai program vaksinasi yang berlaku di kandang.',
    task_type: 'vaksinasi',
    recurring_type: 'bulanan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },
  {
    title: 'Obat cacing ulang (hari ke-60)',
    description: 'Pemberian obat cacing kedua untuk memastikan efektivitas program deworming.',
    task_type: 'obat_cacing',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 59,
    phase_end_offset: 59,
    phase_label: 'Growing',
  },

  // ── FASE FINISHER (Hari 121–150, offset 120–149) ──────────────────────────

  {
    title: 'Beri pakan tinggi energi (konsentrat 80%)',
    description: 'Fase finisher: tingkatkan konsentrat ke 80% untuk percepat penimbunan lemak dan penambahan berat.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 120,
    phase_end_offset: 149,
    phase_label: 'Finisher',
  },
  {
    title: 'Beri pakan sore (finisher)',
    description: 'Pemberian pakan sore fase finisher. Monitor konsumsi pakan untuk deteksi early stress.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:00:00',
    linked_data_entry: false,
    phase_start_offset: 120,
    phase_end_offset: 149,
    phase_label: 'Finisher',
  },
  {
    title: 'Cek kondisi fisik (lemak punggung & postur)',
    description: 'Evaluasi lemak punggung (BCS 3.5–4.0) dan postur untuk menentukan kesiapan panen.',
    task_type: 'kesehatan',
    recurring_type: 'custom',
    recurring_days_of_week: null,
    recurring_interval_days: 3,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 120,
    phase_end_offset: 149,
    phase_label: 'Finisher',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, ganti alas, dan pastikan ventilasi kandang berfungsi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 120,
    phase_end_offset: 149,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang mingguan (monitor target panen)',
    description: 'Timbang mingguan untuk konfirmasi sapi mencapai target berat panen 400–500 kg.',
    task_type: 'timbang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 120,
    phase_end_offset: 149,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang final pra-panen',
    description: 'Timbang final 3 hari sebelum panen untuk konfirmasi berat jual dan estimasi pendapatan.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 147,
    phase_end_offset: 147,
    phase_label: 'Finisher',
  },
]

// ── TEMPLATE 180 HARI (SEMI-INTENSIF) ────────────────────────────────────────

export const TEMPLATE_180_HARI = [

  // ── FASE ADAPTASI (Hari 1–21, offset 0–20) ───────────────────────────────

  {
    title: 'Timbang awal (berat masuk bakalan)',
    description: 'Timbang semua bakalan untuk mencatat berat awal sebagai baseline perhitungan ADG.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Observasi kondisi bakalan baru',
    description: 'Periksa kondisi fisik, nafsu makan, dan tanda stres pada bakalan yang baru masuk.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 20,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Beri pakan adaptasi (hijauan 80%)',
    description: 'Berikan hijauan 80% + konsentrat 20% selama 21 hari adaptasi sistem pencernaan bakalan.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 20,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Cek minum & kebersihan tempat minum',
    description: 'Pastikan tempat minum terisi penuh, bersih, dan tidak ada kotoran atau lumut.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 20,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, ganti alas, dan pastikan ventilasi kandang berfungsi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 20,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Vaksinasi SE + Anthrax',
    description: 'Berikan vaksin Septicemia Epizootica (SE) dan Anthrax sesuai dosis anjuran dokter hewan.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 2,
    phase_end_offset: 2,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Obat cacing (Albendazole)',
    description: 'Berikan Albendazole sesuai bobot badan untuk eliminasi parasit internal bakalan.',
    task_type: 'obat_cacing',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 6,
    phase_end_offset: 6,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Timbang akhir fase adaptasi',
    description: 'Timbang untuk evaluasi performa awal dan konfirmasi adaptasi pakan berjalan baik.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 20,
    phase_end_offset: 20,
    phase_label: 'Adaptasi',
  },

  // ── FASE GROWING (Hari 22–150, offset 21–149) ─────────────────────────────

  {
    title: 'Beri pakan pagi (konsentrat 40%)',
    description: 'Semi-intensif: konsentrat 40% + hijauan 60%. Hijauan bisa dipasok dari kebun sendiri.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Beri pakan sore',
    description: 'Pemberian pakan sore. Pastikan tempat pakan bersih dari sisa pakan sebelumnya.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:00:00',
    linked_data_entry: false,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kesehatan harian',
    description: 'Amati nafsu makan, postur, mata, dan hidung. Catat sapi yang menunjukkan tanda tidak sehat.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, ganti alas, dan pastikan ventilasi kandang berfungsi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Timbang rutin 2 mingguan',
    description: 'Timbang seluruh populasi untuk monitor ADG (Average Daily Gain) fase growing.',
    task_type: 'timbang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Cek & isi stok pakan',
    description: 'Periksa ketersediaan stok konsentrat dan hijauan. Laporkan jika stok tersisa untuk < 7 hari.',
    task_type: 'pakan',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Semprot desinfektan kandang',
    description: 'Semprot desinfektan di seluruh area kandang, termasuk sekat dan tempat minum.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: false,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Vaksinasi booster bulanan',
    description: 'Berikan vaksinasi booster sesuai program vaksinasi yang berlaku di kandang.',
    task_type: 'vaksinasi',
    recurring_type: 'bulanan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 21,
    phase_end_offset: 149,
    phase_label: 'Growing',
  },
  {
    title: 'Obat cacing ulang (hari ke-60)',
    description: 'Pemberian obat cacing kedua untuk memastikan efektivitas program deworming.',
    task_type: 'obat_cacing',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 59,
    phase_end_offset: 59,
    phase_label: 'Growing',
  },
  {
    title: 'Obat cacing ulang (hari ke-120)',
    description: 'Pemberian obat cacing ketiga — tambahan khusus paket 180 hari untuk perlindungan penuh.',
    task_type: 'obat_cacing',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 119,
    phase_end_offset: 119,
    phase_label: 'Growing',
  },

  // ── FASE FINISHER (Hari 151–180, offset 150–179) ──────────────────────────

  {
    title: 'Beri pakan tinggi energi (konsentrat 80%)',
    description: 'Fase finisher: tingkatkan konsentrat ke 80% untuk percepat penimbunan lemak dan penambahan berat.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 150,
    phase_end_offset: 179,
    phase_label: 'Finisher',
  },
  {
    title: 'Beri pakan sore (finisher)',
    description: 'Pemberian pakan sore fase finisher. Monitor konsumsi pakan untuk deteksi early stress.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:00:00',
    linked_data_entry: false,
    phase_start_offset: 150,
    phase_end_offset: 179,
    phase_label: 'Finisher',
  },
  {
    title: 'Cek kondisi fisik (lemak punggung & postur)',
    description: 'Evaluasi lemak punggung (BCS 3.5–4.0) dan postur untuk menentukan kesiapan panen.',
    task_type: 'kesehatan',
    recurring_type: 'custom',
    recurring_days_of_week: null,
    recurring_interval_days: 3,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 150,
    phase_end_offset: 179,
    phase_label: 'Finisher',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, ganti alas, dan pastikan ventilasi kandang berfungsi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 150,
    phase_end_offset: 179,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang mingguan (monitor target panen)',
    description: 'Timbang mingguan untuk konfirmasi sapi mencapai target berat panen 400–500 kg.',
    task_type: 'timbang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 150,
    phase_end_offset: 179,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang final pra-panen',
    description: 'Timbang final 3 hari sebelum panen untuk konfirmasi berat jual dan estimasi pendapatan.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 177,
    phase_end_offset: 177,
    phase_label: 'Finisher',
  },
]
