/**
 * TernakOS Default Task Templates — Ayam Broiler
 * Berdasarkan standar pemeliharaan ayam broiler di Indonesia (~35 hari).
 *
 * task_type enum: 'pakan' | 'timbang' | 'vaksinasi' | 'kesehatan' | 'kebersihan_kandang' | 'recording_harian' | 'brooding_check' | 'lainnya'
 * recurring_type enum: 'harian' | 'mingguan' | 'dua_mingguan' | 'bulanan' | 'custom' | 'sekali'
 */

// ── TEMPLATE 35 HARI (STANDAR BROILER) ────────────────────────────────────────

export const TEMPLATE_BROILER_35 = [

  // ── FASE BROODING (Hari 1–7, offset 0–6) ─────────────────────────────────

  {
    title: 'Cek suhu & kelembaban brooder',
    description: 'Pastikan suhu brooder 32–35°C (hari 1–3) lalu turunkan bertahap. Kelembaban 60–70%.',
    task_type: 'brooding_check',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 6,
    phase_label: 'Brooding',
  },
  {
    title: 'Catat mortalitas harian',
    description: 'Hitung dan catat jumlah ayam mati. Pisahkan bangkai untuk pemeriksaan.',
    task_type: 'recording_harian',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 6,
    phase_label: 'Brooding',
  },
  {
    title: 'Beri pakan starter (crumble)',
    description: 'Sebar pakan starter pada chick tray & tempat pakan. Pastikan semua DOC mendapat akses pakan merata.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 6,
    phase_label: 'Brooding',
  },
  {
    title: 'Cek air minum + vitamin/elektrolit',
    description: 'Pastikan nipple/bell drinker berfungsi baik. Tambahkan vitamin & elektrolit anti-stress di air minum.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 6,
    phase_label: 'Brooding',
  },
  {
    title: 'Vaksinasi ND-B1 (tetes mata)',
    description: 'Berikan vaksin Newcastle Disease B1 via tetes mata pada hari ke-4.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 3,
    phase_end_offset: 3,
    phase_label: 'Brooding',
  },
  {
    title: 'Pembersihan litter & tempat pakan',
    description: 'Bersihkan litter yang basah/cake. Cuci tempat pakan dan tempat minum.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 6,
    phase_label: 'Brooding',
  },

  // ── FASE GROWING (Hari 8–28, offset 7–27) ────────────────────────────────

  {
    title: 'Beri pakan grower',
    description: 'Ganti pakan ke grower (pellet). Pastikan konsumsi pakan sesuai standar umur.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:00:00',
    linked_data_entry: true,
    phase_start_offset: 7,
    phase_end_offset: 27,
    phase_label: 'Growing',
  },
  {
    title: 'Catat mortalitas & culling',
    description: 'Hitung ayam mati dan culling. Catat penyebab jika teridentifikasi.',
    task_type: 'recording_harian',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 7,
    phase_end_offset: 27,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kondisi litter & ventilasi',
    description: 'Periksa kelembaban litter (harus kering & gembur). Pastikan ventilasi berfungsi optimal.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 7,
    phase_end_offset: 27,
    phase_label: 'Growing',
  },
  {
    title: 'Timbang sampel bobot (10% populasi)',
    description: 'Ambil sampel 10% populasi untuk timbang bobot rata-rata. Bandingkan dengan standar.',
    task_type: 'timbang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 7,
    phase_end_offset: 27,
    phase_label: 'Growing',
  },
  {
    title: 'Vaksinasi IBD/Gumboro',
    description: 'Berikan vaksin Infectious Bursal Disease via air minum pada hari ke-12.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 11,
    phase_end_offset: 11,
    phase_label: 'Growing',
  },
  {
    title: 'Vaksinasi ND Booster (La Sota)',
    description: 'Berikan vaksin ND La Sota via air minum pada hari ke-18.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 17,
    phase_end_offset: 17,
    phase_label: 'Growing',
  },
  {
    title: 'Semprot desinfektan kandang',
    description: 'Semprot desinfektan di seluruh area, terutama di sekitar tempat minum.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [3],
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 7,
    phase_end_offset: 27,
    phase_label: 'Growing',
  },

  // ── FASE PRE-PANEN (Hari 29–35, offset 28–34) ────────────────────────────

  {
    title: 'Beri pakan finisher',
    description: 'Ganti ke pakan finisher. Tidak boleh ada tambahan antibiotik (masa withdrawal).',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:00:00',
    linked_data_entry: true,
    phase_start_offset: 28,
    phase_end_offset: 34,
    phase_label: 'Pre-Panen',
  },
  {
    title: 'Catat mortalitas & estimasi populasi akhir',
    description: 'Hitung mortalitas. Estimasi jumlah ayam hidup untuk persiapan panen.',
    task_type: 'recording_harian',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 28,
    phase_end_offset: 34,
    phase_label: 'Pre-Panen',
  },
  {
    title: 'Timbang sampel harian (estimasi bobot panen)',
    description: 'Timbang sampel harian untuk estimasi bobot rata-rata saat panen.',
    task_type: 'timbang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 28,
    phase_end_offset: 34,
    phase_label: 'Pre-Panen',
  },
  {
    title: 'Puasakan ayam 8 jam sebelum panen',
    description: 'Stop pemberian pakan 8 jam sebelum jadwal pengangkutan. Air minum tetap tersedia.',
    task_type: 'lainnya',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '22:00:00',
    linked_data_entry: false,
    phase_start_offset: 33,
    phase_end_offset: 33,
    phase_label: 'Pre-Panen',
  },
]
