/**
 * TernakOS Default Task Templates — Domba
 * Penggemukan (~90 hari) dan Breeding (siklus reproduksi).
 * Domba berbeda dari kambing: siklus birahi ±17 hari, kebuntingan ±147 hari,
 * perlu perhatian bulu/wool, dan lebih rentan terhadap parasit.
 *
 * task_type enum: 'pakan' | 'timbang' | 'vaksinasi' | 'kesehatan' | 'kebersihan_kandang' | 'reproduksi' | 'bcs_check' | 'wool_check' | 'lainnya'
 */

// ── TEMPLATE DOMBA PENGGEMUKAN 90 HARI ────────────────────────────────────────

export const TEMPLATE_DOMBA_PENGGEMUKAN_90 = [

  // ── FASE ADAPTASI (Hari 1–14, offset 0–13) ──────────────────────────────

  {
    title: 'Timbang awal (berat masuk)',
    description: 'Timbang semua domba bakalan untuk baseline ADG.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Cek BCS & kondisi bulu awal',
    description: 'Evaluasi BCS (skala 1–5) dan kondisi bulu/wool domba masuk.',
    task_type: 'bcs_check',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:30:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Observasi kondisi bakalan',
    description: 'Periksa kondisi fisik, nafsu makan, kuku, dan tanda penyakit.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Beri pakan adaptasi (hijauan 70%)',
    description: 'Hijauan 70% + konsentrat 30%. Domba membutuhkan transisi pakan bertahap.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, cek kelembaban lantai (domba sensitif terhadap lantai basah).',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Vaksinasi SE + Anthrax',
    description: 'Berikan vaksin SE dan Anthrax sesuai dosis.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 3,
    phase_end_offset: 3,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Obat cacing + spray anti-ektoparasit',
    description: 'Obat cacing oral + spray kutu/tungau (domba lebih rentan ektoparasit).',
    task_type: 'kesehatan',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 5,
    phase_end_offset: 5,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Pemberian vitamin & booster nafsu makan',
    description: 'Injeksi vitamin B-kompleks atau suplemen pendukung untuk pemulihan stres perjalanan.',
    task_type: 'kesehatan',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 7,
    phase_end_offset: 7,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Cukur bulu awal (Shearing)',
    description: 'Cukur bulu gimbal/kotor agar domba lebih nyaman, tidak kegerahan, dan mempermudah penetrasi obat kutu.',
    task_type: 'wool_check',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 10,
    phase_end_offset: 10,
    phase_label: 'Adaptasi',
  },

  // ── FASE GROWING (Hari 15–75, offset 14–74) ──────────────────────────────

  {
    title: 'Beri pakan pagi (konsentrat 50%)',
    description: 'Pakan pagi: konsentrat 50% + hijauan 50%.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kesehatan harian',
    description: 'Amati nafsu makan, postur, mata, dan kondisi bulu. Domba cenderung menyembunyikan gejala sakit.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, cek lantai & drainase.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Timbang rutin 2 mingguan',
    description: 'Timbang untuk monitor ADG.',
    task_type: 'timbang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kondisi bulu & kulit',
    description: 'Periksa adanya parasit atau jamur (scabies/ringworm). Domba perlu perhatian ekstra di balik wool.',
    task_type: 'wool_check',
    recurring_type: 'mingguan',
    recurring_days_of_week: [3],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Potong kuku (Hoof Trim)',
    description: 'Periksa dan potong kuku yang mulai memanjang untuk mencegah busuk kuku (foot rot).',
    task_type: 'kesehatan',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 45,
    phase_end_offset: 45,
    phase_label: 'Growing',
  },

  // ── FASE FINISHER (Hari 76–90, offset 75–89) ─────────────────────────────

  {
    title: 'Beri pakan finisher (konsentrat 60%)',
    description: 'Tingkatkan konsentrat ke 60% untuk percepat penambahan berat.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 75,
    phase_end_offset: 89,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang mingguan (target panen)',
    description: 'Timbang mingguan untuk konfirmasi target berat panen.',
    task_type: 'timbang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 75,
    phase_end_offset: 89,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang final pra-panen',
    description: 'Timbang final 3 hari sebelum panen.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 87,
    phase_end_offset: 87,
    phase_label: 'Finisher',
  },
]

// ── TEMPLATE DOMBA BREEDING (SIKLUS REPRODUKSI) ──────────────────────────────

export const TEMPLATE_DOMBA_BREEDING = [
  {
    title: 'Deteksi birahi (estrus)',
    description: 'Amati tanda birahi domba: gelisah, menggoyang ekor, vulva bengkak. Siklus birahi domba ±17 hari (lebih pendek dari kambing).',
    task_type: 'reproduksi',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 25,
    phase_label: 'Deteksi Birahi',
  },
  {
    title: 'Evaluasi BCS induk',
    description: 'Pastikan BCS induk 3.0–3.5 sebelum kawin. Perhatikan kondisi bulu dan kuku.',
    task_type: 'bcs_check',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 25,
    phase_label: 'Deteksi Birahi',
  },
  {
    title: 'Beri pakan induk',
    description: 'Pakan induk: hijauan + konsentrat protein tinggi.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 200,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Cek kesehatan & kondisi bulu induk',
    description: 'Cek kondisi fisik induk termasuk bulu, ambing, dan kuku.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 200,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kandang, pastikan lantai kering (domba sensitif lantai basah).',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 200,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Cek kebuntingan (palpasi/USG)',
    description: 'Konfirmasi kebuntingan 45 hari setelah kawin. Masa bunting domba ±147 hari.',
    task_type: 'reproduksi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 70,
    phase_end_offset: 70,
    phase_label: 'Kebuntingan',
  },
  {
    title: 'Cek kondisi bulu pra-kelahiran',
    description: 'Cukur bulu di sekitar ambing dan area belakang menjelang kelahiran.',
    task_type: 'wool_check',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 160,
    phase_end_offset: 160,
    phase_label: 'Kelahiran',
  },
  {
    title: 'Persiapan kandang kelahiran',
    description: 'Siapkan kandang bersalin: bersihkan, beri alas kering, sediakan handuk & iodine.',
    task_type: 'lainnya',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 165,
    phase_end_offset: 165,
    phase_label: 'Kelahiran',
  },
]

// ── TEMPLATE DOMBA PENGGEMUKAN INTENSIF (PRECISION 1-45-90) ──────────────────

export const TRIGGERED_MEDICAL_INTERVENTION = {
  title: 'Intervensi Medis: Obat Cacing & Vitamin',
  description: 'Urgent: Skor FAMACHA 4/5 Terdeteksi. Pemberian B-Drench & Injeksi Vitamin B-Complex.',
  task_type: 'kesehatan',
  recurring_type: 'sekali',
  due_time: '09:00:00',
  linked_data_entry: true,
  phase_label: 'Kesehatan Khusus',
  is_conditional: true,
}

export const TEMPLATE_DOMBA_INTENSIF_90 = [
  // ── TITIK KRITIS TIMBANG TOTAL (1-45-90) ──
  {
    title: 'Timbang Bakalan (Total 100%)',
    description: 'Recording berat awal semua populasi sebagai baseline ADG.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Bakalan Masuk',
  },
  {
    title: 'Timbang Evaluasi (Total 100%)',
    description: 'Evaluasi pertumbuhan tengah periode untuk penyesuaian pakan/suplemen.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 45,
    phase_end_offset: 45,
    phase_label: 'Evaluasi 45 Hari',
  },
  {
    title: 'Timbang Final Panen (Total 100%)',
    description: 'Recording bobot akhir dan grading kualitas untuk penentuan harga jual.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 90,
    phase_end_offset: 90,
    phase_label: 'Panen',
  },

  // ── MONITORING RUTIN (Randomized Sampling 10%) ──
  {
    title: 'Timbang Sampling (Random 10%) & FAMACHA',
    description: 'Monitor ADG populasi & skor anemia kelopak mata tanpa membuat stress domba.',
    task_type: 'timbang',
    recurring_type: 'dua_mingguan',
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 89,
    phase_label: 'Monitoring Akurasi',
  },

  // ── OPERASIONAL HARIAN (Batch Oriented) ──
  {
    title: 'Manajemen Pakan Pagi (The 70/30 Rule)',
    description: 'Cek sisa pakan (Habis/Sedikit/Banyak) & pemberian porsi pagi (60%).',
    task_type: 'pakan',
    recurring_type: 'harian',
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 90,
    phase_label: 'Operasional',
  },
  {
    title: 'Manajemen Pakan Sore',
    description: 'Pemberian porsi serat/hijauan (40%) dan monitoring kebersihan air minum.',
    task_type: 'pakan',
    recurring_type: 'harian',
    due_time: '16:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 90,
    phase_label: 'Operasional',
  },
  {
    title: 'Pembersihan Palung & Sanitasi',
    description: 'Pengangkatan sisa pakan (orts) dan pembersihan area pakan untuk hygiene maksimal.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 90,
    phase_label: 'Operasional',
  },

  // ── MEDICAL INTERVENTION (Conditional / Automated) ──
  {
    ...TRIGGERED_MEDICAL_INTERVENTION,
    phase_start_offset: 0,
    phase_end_offset: 90,
  },
]

