/**
 * TernakOS Default Task Templates — Kambing
 * Penggemukan (~90 hari) dan Breeding (siklus reproduksi).
 *
 * task_type enum: 'pakan' | 'timbang' | 'vaksinasi' | 'kesehatan' | 'kebersihan_kandang' | 'reproduksi' | 'bcs_check' | 'lainnya'
 */

// ── TEMPLATE KAMBING PENGGEMUKAN 90 HARI ──────────────────────────────────────

export const TEMPLATE_KAMBING_PENGGEMUKAN_90 = [

  // ── FASE ADAPTASI (Hari 1–14, offset 0–13) ──────────────────────────────

  {
    title: 'Timbang awal (berat masuk)',
    description: 'Timbang semua kambing bakalan untuk baseline ADG.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Cek Body Condition Score (BCS) awal',
    description: 'Evaluasi BCS semua kambing masuk (skala 1–5). Target masuk: BCS 2.0–2.5.',
    task_type: 'bcs_check',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:30:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 0,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Observasi kondisi bakalan',
    description: 'Periksa kondisi fisik, nafsu makan, tanda stres, dan penyakit pada kambing baru.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Beri pakan adaptasi (hijauan 70%)',
    description: 'Berikan hijauan 70% + konsentrat 30% untuk adaptasi rumen kambing bakalan.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran dari panggung, cek drainase, dan pastikan ventilasi baik.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 13,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Vaksinasi SE + Anthrax',
    description: 'Berikan vaksin SE dan Anthrax sesuai dosis.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 3,
    phase_end_offset: 3,
    phase_label: 'Adaptasi',
  },
  {
    title: 'Obat cacing (Albendazole)',
    description: 'Berikan obat cacing oral sesuai bobot badan.',
    task_type: 'kesehatan',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 5,
    phase_end_offset: 5,
    phase_label: 'Adaptasi',
  },

  // ── FASE GROWING (Hari 15–75, offset 14–74) ──────────────────────────────

  {
    title: 'Beri pakan pagi (konsentrat 50%)',
    description: 'Pakan pagi: konsentrat 50% + hijauan 50%. Pastikan semua kambing mendapat porsi merata.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Beri pakan sore',
    description: 'Pemberian pakan sore. Bersihkan sisa pakan sebelumnya.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Cek kesehatan harian',
    description: 'Amati nafsu makan, postur, mata, hidung, dan kotoran. Catat kambing bermasalah.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, cek lantai panggung, dan ventilasi.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Timbang rutin 2 mingguan',
    description: 'Timbang seluruh hewan untuk monitor ADG.',
    task_type: 'timbang',
    recurring_type: 'dua_mingguan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },
  {
    title: 'Evaluasi BCS bulanan',
    description: 'Evaluasi Body Condition Score semua kambing. Target growing: BCS 2.5–3.5.',
    task_type: 'bcs_check',
    recurring_type: 'bulanan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 14,
    phase_end_offset: 74,
    phase_label: 'Growing',
  },

  // ── FASE FINISHER (Hari 76–90, offset 75–89) ─────────────────────────────

  {
    title: 'Beri pakan finisher (konsentrat 60%)',
    description: 'Tingkatkan konsentrat ke 60% untuk percepat penambahan berat menjelang panen.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 75,
    phase_end_offset: 89,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang mingguan (target panen)',
    description: 'Timbang mingguan untuk konfirmasi kambing mencapai target berat panen.',
    task_type: 'timbang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 75,
    phase_end_offset: 89,
    phase_label: 'Finisher',
  },
  {
    title: 'Timbang final pra-panen',
    description: 'Timbang final 3 hari sebelum panen untuk konfirmasi berat jual.',
    task_type: 'timbang',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 87,
    phase_end_offset: 87,
    phase_label: 'Finisher',
  },
]

// ── TEMPLATE KAMBING BREEDING (SIKLUS REPRODUKSI) ─────────────────────────────

export const TEMPLATE_KAMBING_BREEDING = [
  {
    title: 'Deteksi birahi (estrus)',
    description: 'Amati tanda birahi: gelisah, ekor mengibas, vulva bengkak/merah, menaiki sesama. Siklus birahi kambing ±21 hari.',
    task_type: 'reproduksi',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 30,
    phase_label: 'Deteksi Birahi',
  },
  {
    title: 'Evaluasi BCS induk',
    description: 'Pastikan BCS induk 3.0–3.5 sebelum proses perkawinan.',
    task_type: 'bcs_check',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 30,
    phase_label: 'Deteksi Birahi',
  },
  {
    title: 'Beri pakan induk',
    description: 'Pakan induk: hijauan berkualitas + konsentrat protein tinggi.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 210,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Cek kesehatan induk',
    description: 'Cek kondisi fisik induk, termasuk ambing dan kuku.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '07:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 210,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kandang, cek lantai panggung, dan ventilasi.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 210,
    phase_label: 'Pemeliharaan',
  },
  {
    title: 'Cek kebuntingan (palpasi/USG)',
    description: 'Konfirmasi kebuntingan 45 hari setelah kawin terakhir. Masa bunting kambing ±150 hari.',
    task_type: 'reproduksi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 75,
    phase_end_offset: 75,
    phase_label: 'Kebuntingan',
  },
  {
    title: 'Vaksinasi induk bunting',
    description: 'Berikan vaksin Clostridium 1 bulan sebelum perkiraan lahir.',
    task_type: 'vaksinasi',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: true,
    phase_start_offset: 150,
    phase_end_offset: 150,
    phase_label: 'Kebuntingan',
  },
  {
    title: 'Persiapan kandang kelahiran',
    description: 'Siapkan kandang bersalin: bersihkan, beri alas kering, sediakan handuk & iodine.',
    task_type: 'lainnya',
    recurring_type: 'sekali',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: false,
    phase_start_offset: 170,
    phase_end_offset: 170,
    phase_label: 'Kelahiran',
  },
]
