/**
 * TernakOS Default Task Templates — Sapi Perah
 * Berbasis siklus laktasi harian, bukan batch penggemukan.
 *
 * task_type enum: 'perah_susu' | 'pakan' | 'kesehatan' | 'kebersihan_kandang' | 'reproduksi' | 'cmt_check' | 'bcs_check' | 'timbang' | 'lainnya'
 */

export const TEMPLATE_SAPI_PERAH_HARIAN = [

  // ── TUGAS HARIAN (recurring setiap hari) ─────────────────────────────────

  {
    title: 'Perah susu pagi',
    description: 'Lakukan pemerahan pagi. Catat volume per ekor. Pastikan pelvis & ambing bersih sebelum perah.',
    task_type: 'perah_susu',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '05:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Perah susu sore',
    description: 'Lakukan pemerahan sore. Catat volume. Bandingkan dengan produksi pagi.',
    task_type: 'perah_susu',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Beri pakan pagi (konsentrat + hijauan)',
    description: 'Pakan pagi: konsentrat sesuai produksi susu + hijauan segar.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '05:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Beri pakan sore',
    description: 'Pakan sore. Bersihkan tempat pakan dari sisa.',
    task_type: 'pakan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '15:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Cek kesehatan harian',
    description: 'Periksa nafsu makan, kondisi ambing, suhu tubuh, dan kotoran. Catat sapi bermasalah.',
    task_type: 'kesehatan',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Cuci peralatan perah',
    description: 'Cuci dan sterilkan semua peralatan perah setelah digunakan.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '06:30:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Pembersihan kandang',
    description: 'Bersihkan kotoran, bilas lantai, cek drainase.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'harian',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '16:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },

  // ── TUGAS MINGGUAN ───────────────────────────────────────────────────────

  {
    title: 'Tes CMT (California Mastitis Test)',
    description: 'Lakukan tes CMT pada semua sapi perah untuk deteksi dini mastitis. Catat hasilnya per kuartir.',
    task_type: 'cmt_check',
    recurring_type: 'mingguan',
    recurring_days_of_week: [1],
    recurring_interval_days: null,
    due_time: '05:30:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Semprot desinfektan kandang & peralatan',
    description: 'Desinfeksi menyeluruh area kandang dan peralatan perah.',
    task_type: 'kebersihan_kandang',
    recurring_type: 'mingguan',
    recurring_days_of_week: [6],
    recurring_interval_days: null,
    due_time: '09:00:00',
    linked_data_entry: false,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },

  // ── TUGAS BULANAN ────────────────────────────────────────────────────────

  {
    title: 'Evaluasi BCS bulanan',
    description: 'Evaluasi BCS semua sapi perah. Target laktasi: BCS 2.5–3.5.',
    task_type: 'bcs_check',
    recurring_type: 'bulanan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Recording reproduksi',
    description: 'Update status reproduksi semua induk: bunting, masa kering, birahi, post-partum.',
    task_type: 'reproduksi',
    recurring_type: 'bulanan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
  {
    title: 'Timbang produksi susu total',
    description: 'Timbang dan catat total produksi susu bulan ini per ekor.',
    task_type: 'timbang',
    recurring_type: 'bulanan',
    recurring_days_of_week: null,
    recurring_interval_days: null,
    due_time: '08:00:00',
    linked_data_entry: true,
    phase_start_offset: 0,
    phase_end_offset: 365,
    phase_label: 'Laktasi',
  },
]
